//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Горводоканал
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Вид обращени.
    /// </summary>
    // *** Start programmer edit section *** (ВидОбращени CustomAttributes)

    // *** End programmer edit section *** (ВидОбращени CustomAttributes)
    [AutoAltered()]
    [ICSSoft.STORMNET.NotStored(false)]
    [Caption("Вид обращени")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ВидОбращениE", new string[] {
            "Название as \'Название\'",
            "Код as \'Код\'",
            "Актуально as \'Актуально\'",
            "ТипОбращения as \'Тип обращения\'"})]
    [MasterViewDefineAttribute("ВидОбращениE", "ТипОбращения", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Название")]
    [View("ВидОбращениL", new string[] {
            "Название as \'Название\'",
            "Код as \'Код\'",
            "Актуально as \'Актуально\'",
            "ТипОбращения.Название as \'Название\'"})]
    public class ВидОбращени : IIS.Горводоканал.Справочник
    {
        
        private string fНазвание;
        
        private int fКод;
        
        private IIS.Горводоканал.ТипОбращения fТипОбращения;
        
        // *** Start programmer edit section *** (ВидОбращени CustomMembers)

        // *** End programmer edit section *** (ВидОбращени CustomMembers)

        
        /// <summary>
        /// Название.
        /// </summary>
        // *** Start programmer edit section *** (ВидОбращени.Название CustomAttributes)

        // *** End programmer edit section *** (ВидОбращени.Название CustomAttributes)
        [StrLen(150)]
        [NotNull()]
        public virtual string Название
        {
            get
            {
                // *** Start programmer edit section *** (ВидОбращени.Название Get start)

                // *** End programmer edit section *** (ВидОбращени.Название Get start)
                string result = this.fНазвание;
                // *** Start programmer edit section *** (ВидОбращени.Название Get end)

                // *** End programmer edit section *** (ВидОбращени.Название Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ВидОбращени.Название Set start)

                // *** End programmer edit section *** (ВидОбращени.Название Set start)
                this.fНазвание = value;
                // *** Start programmer edit section *** (ВидОбращени.Название Set end)

                // *** End programmer edit section *** (ВидОбращени.Название Set end)
            }
        }
        
        /// <summary>
        /// Код.
        /// </summary>
        // *** Start programmer edit section *** (ВидОбращени.Код CustomAttributes)

        // *** End programmer edit section *** (ВидОбращени.Код CustomAttributes)
        public virtual int Код
        {
            get
            {
                // *** Start programmer edit section *** (ВидОбращени.Код Get start)

                // *** End programmer edit section *** (ВидОбращени.Код Get start)
                int result = this.fКод;
                // *** Start programmer edit section *** (ВидОбращени.Код Get end)

                // *** End programmer edit section *** (ВидОбращени.Код Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ВидОбращени.Код Set start)

                // *** End programmer edit section *** (ВидОбращени.Код Set start)
                this.fКод = value;
                // *** Start programmer edit section *** (ВидОбращени.Код Set end)

                // *** End programmer edit section *** (ВидОбращени.Код Set end)
            }
        }
        
        /// <summary>
        /// Вид обращени.
        /// </summary>
        // *** Start programmer edit section *** (ВидОбращени.ТипОбращения CustomAttributes)

        // *** End programmer edit section *** (ВидОбращени.ТипОбращения CustomAttributes)
        [PropertyStorage(new string[] {
                "ТипОбращения"})]
        public virtual IIS.Горводоканал.ТипОбращения ТипОбращения
        {
            get
            {
                // *** Start programmer edit section *** (ВидОбращени.ТипОбращения Get start)

                // *** End programmer edit section *** (ВидОбращени.ТипОбращения Get start)
                IIS.Горводоканал.ТипОбращения result = this.fТипОбращения;
                // *** Start programmer edit section *** (ВидОбращени.ТипОбращения Get end)

                // *** End programmer edit section *** (ВидОбращени.ТипОбращения Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ВидОбращени.ТипОбращения Set start)

                // *** End programmer edit section *** (ВидОбращени.ТипОбращения Set start)
                this.fТипОбращения = value;
                // *** Start programmer edit section *** (ВидОбращени.ТипОбращения Set end)

                // *** End programmer edit section *** (ВидОбращени.ТипОбращения Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ВидОбращениE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ВидОбращениE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ВидОбращениE", typeof(IIS.Горводоканал.ВидОбращени));
                }
            }
            
            /// <summary>
            /// "ВидОбращениL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ВидОбращениL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ВидОбращениL", typeof(IIS.Горводоканал.ВидОбращени));
                }
            }
        }
    }
}
